# Python Tutorial

In [1]:
print('Hello World')

Hello World


Jupyter prints out the return value of the last line

In [2]:
'Hello World' 

'Hello World'

## Arithmetics

In [3]:
print(1 + 1)   # => 2
print(8 - 1)   # => 7
print(10 * 2)  # => 20
print(10.0 * 2) # => 20.0
print(10 * 2.0) # => 20.0

2
7
20
20.0
20.0


### Divisions

In [4]:
#Always return a float
print(35 / 5)  # => 7.0
print(10.0 / 3)  # => 3.3333333333333335

# Truncates down for integers when double stash //
print(5 // 3)      # => 1
print(5.0 // 3.0)   # => 1.0 # works on floats too
print(-5 // 3)      # => -2
print(-5.0 // 3.0)  # => -2.0


7.0
3.3333333333333335
1
1.0
-2
-2.0


### Modulo operatior, i.e. remainder

In [5]:
print(7 % 3)  # => 1

1


### Exponentials (x**y, x to the yth power)

Works not only to positive integer powers but to negative and fractional powers

In [6]:
print(2**3) #=> 8
print(4**.5) #=> 2.0

8
2.0


## Boolean Logics

Booleans: True, False. Python is Case-sensitive! true will refer to a variable named 'true'. The 't' and 'f' MUST be uppercase.


In [7]:
print(True and False)  # => False
print(False or True)   # => True
print(not True)   # => False
print(not False)  # => True
print(2 == 1)  # => False
print(1 != 1)  # => False
print(1 > 10)  # => False
print(2 <= 2)  # => True

False
True
False
True
False
False
False
True


## Variables

In [8]:
# No type declaration required
some_var = 5
print(some_var)  # => 5
# Can use the same variable for different data types
some_var = float(some_var)
print(some_var) #=> 5.0 (The “.0” indicates a float)

5
5.0


## Strings

In [9]:
# "" and '' are the same
somestring = "I am some string."
print(somestring) # => I am some string.

I am some string.


In [10]:
# Use + to concat strings
string_a = "I am"
string_b = " a single string."
string_c = string_a + string_b
print(string_c) #=> I am a single string.

I am a single string.


In [11]:
# Use * to repeat strings
print('ha'*10)

hahahahahahahahahaha


In [12]:
#print stings with variables
answer = 42
#choice 1:
print('This is my integer:', answer)
#choice 2:
print('This is my integer: {}'.format(answer))    

#choice 2 is mostly prefered as the string looks cleaner.

This is my integer: 42
This is my integer: 42


## Arrays/Lists

Arrays in python are commonly referred to lists, but they are actually dynamic arrays.

## Creating Lists

In [13]:
# Lists store sequences
li = []
# You can start with a prefilled list
other_li = [4, 5, 6]
some_2d_array = [[2,2],[3,4]]
another_li = [4]*3  #another_li is now [4,4,4]

print(len(other_li)) #=> 3
print(li) #=> []
print(some_2d_array) #=> [[2, 2], [3, 4]]
print(another_li) #=> [4, 4, 4]

3
[]
[[2, 2], [3, 4]]
[4, 4, 4]


## Append Items

In [14]:
#Add stuff to the end of a list with append
li.append(1)    # li is now [1]
li.append(2)    # li is now [1, 2]
print(li) #=> [1, 2]

[1, 2]


## Accessing list elements

In [15]:
# Access a list like you would any array
print(li[0])   # => 1
print(li[1])   # => 2
# Look at the last element
print(li[-1]) # => 2
# Look at the second last element
print(li[-2])  # => 1
print(some_2d_array[1][0]) # => 3

1
2
2
1
3


In [16]:
# You can look at sub-lists with slice syntax.
li = [1,2,4,3]
# The start index is included, the end index is not
print(li[1:3])   # => [2, 4]
# Omitting the end means get until the end
print(li[2:])    # => [4, 3]
# Omitting the beginning means start from the beginning
print(li[:3])    # => [1, 2, 4]
# Select every second entry
print(li[::2])   # =>[1, 4]
# Return a reversed copy of the list
print(li[::-1])  # => [3, 4, 2, 1]
# Use any combination of these to make advanced slices
# li[start:end:step]


[2, 4]
[4, 3]
[1, 2, 4]
[1, 4]
[3, 4, 2, 1]


## If

Here is an if statement.
**Indentation is significant in Python!** Indentation defines the scope of the code. Omitting them will result in syntax error.
Convention is to use four spaces, not tabs.

In [17]:
some_var = 5

if some_var > 10:
    print("some_var is totally bigger than 10.")
elif some_var < 10:    # This elif clause is optional.
    print("some_var is smaller than 10.")
else:                  # This is optional too.
    print("some_var is indeed 10.")

#Ternary operator
some_var = 10 if 3 > 2 else 11 #=> some_var == 10
print(some_var)
some_var = 10 if 20 > 100 else 11 #=> some_var == 11
print(some_var)

some_var is smaller than 10.
10
11


## For Loops

For loops in python are a bit different from languages like c and java. 
For loops iterate over lists.

In [18]:
"""
prints:
    dog is a mammal
    cat is a mammal
    mouse is a mammal
"""
for animal in ["dog", "cat", "mouse"]:
    #Remember indentation matters!
    print(animal,"is a mammal")


dog is a mammal
cat is a mammal
mouse is a mammal


"range(number)" returns an iterable of numbers from zero to the given number

In [19]:
primes = [2,3,5,7,11,13]
for i in range(len(primes)):
    primes[i] **= 2
print(primes)

[4, 9, 25, 49, 121, 169]


Using "for i in range(n):" we can also obtain the classical for loop

for (int i = 0; i<n; i++){...

In [20]:
for i in range(4): #=> 0 1 2 3
    print(i)
print('\n')

for i in range(4, 8): #=> 4 5 6 7
    print(i)
print('\n')

for i in range(4, 8, 2): #=> 4 6
    print(i)
print('\n')


0
1
2
3


4
5
6
7


4
6




To loop over two lists at the same time use **zip()**

In [21]:
list_a = [3,4,5]
list_b = [9,7,1]
for first, second in zip(list_a, list_b):
    print(first, second)

3 9
4 7
5 1


**enumerate()** returns the index and element of a list

In [22]:
my_list = ['fortran', 'windows', 'ide with white backgrounds']
for index, element in enumerate(my_list):
    my_list[index] = 'I like ' + element
print(my_list)

['I like fortran', 'I like windows', 'I like ide with white backgrounds']


## Control Flows

### Break

Ends the loop prematurely.

In [23]:
x = 0
for i in range(1,10):
    x += i
    if x > 20:
        print(x, i)
        break

21 6


### Continue

Skip the remaining code and go to the next iteration.

In [24]:
x = [1,6,1,0,7,4]
for i, el in enumerate(x):
    if el == 0:
        continue
    x[i] = 1/el
print(x)
    

[1.0, 0.16666666666666666, 1.0, 0, 0.14285714285714285, 0.25]


### For Else

Pretty unique to python. Executes when no **break** is called inside the for loop.

In [25]:
my_list = [9,4,1,7,4,9,2]
for index, element in enumerate(my_list):
    if element == 5:
        print('Index {} is 5'.format(index))
        break
else:
    print('5 not in the list')

5 not in the list


## While Loops

while loops in Python are pretty similar to most programming languages. However they are not used that often in python compared to for loops.

In [26]:
x = 0
while x < 4: # 0 1 2 3
    print(x)
    x += 1
print('\n')

x = 0
i = 0
while x < 20:
    i += 1
    x += i
print(x, i)

0
1
2
3


21 6


### Tuples are like lists but are immutable.

In [27]:
tup = (1, 2, 3)
print(tup[0])      # => 1
#tup[0] = 3  # Raises a TypeError

1


Tuples are useful in python because they can be 'unpacked'.

In [28]:
# You can unpack tuples (or lists) into variables
a, b, c = (1, 2, 3)  # a is now 1, b is now 2 and c is now 3
print(a, b, c)

# Tuples are created by default if you leave out the parentheses
d, e, f = 4, 5, 6
print(d, e, f)

# Now look how easy it is to swap two values
e, d = d, e  # d is now 5 and e is now 4
print(d, e)

1 2 3
4 5 6
5 4


A "*" in front of a variable on the left side means to receive all the extra terms as parse it as a list

In [29]:
# You can also do extended unpacking
a, *b, c = (1, 2, 3, 4)  # a is now 1, b is now [2, 3] and c is now 4
print(a, b, c)


1 [2, 3] 4


## Functions

In [30]:
# Use "def" to create new functions
def add(x, y):
    print("x is {} and y is {}".format(x, y))
    return x + y  # Return values with a return statement

In [31]:
#prints out "x is 5 and y is 6" and returns 11
results = add(5, 6)
print(results)

x is 5 and y is 6
11


Another way to call functions is with keyword arguments. Keyword arguments can arrive in any order.

In [32]:
print(add(y=6, x=5))

x is 5 and y is 6
11


A "*" in front of a input means to distribute the tuple/list to all arguments in order

In [33]:
inputs = (1,2)
print(add(*inputs))

inputs = [1,2]
print(add(*inputs))

x is 1 and y is 2
3
x is 1 and y is 2
3


A "*" in front of an argument means to recieve a variable amount of inputs and parse it as a tuple

In [34]:
def varargs(*args):
    print(args)
varargs(1, 2, 3)  # => (1, 2, 3)0

(1, 2, 3)


## Objects

Functions with style like \__init__ are special functions and should not be arbitary named. Each of them serve a special purpose

In [35]:
class Particle(): # CamelCase by convention
    name = "neutron"

    def __init__(self, x, y, vx, vy):
        self.x = x
        self.y = y
        self.vx = vx
        self.vy = vy

    def move_right(self, distance):
        self.x += distance

    # A property is just like a getter.
    # It turns the method mass() into an read-only attribute of the same name.
    # There's no need to write trivial getters and setters in Python, though.
    @property
    def energy(self):
        return self._energy

    # This allows the property to be set
    @energy.setter
    def energy(self, energy):
        assert energy>0, "Energy must be larger than zero" # Don’t argue, this is the relativistic energy 
        self._energy = energy

    # This allows the property to be deleted
    @energy.deleter
    def energy(self):
        del self._energy

   # particle_a and particle_b are instances of type Particle, or in other words: they are Particle objects
particle_a = Particle(1,2,3,4)
particle_b = Particle(5,6,7,8)
print(particle_a.x) #=> 1
print(particle_b.y) #=> 6

particle_a.move_right(10)
print(particle_a.x) #=> 11

particle_a.energy = 10
print(particle_a.energy) #=> 10

#particle_a.energy = 0 #=> assertion Error: Energy must be larger than zero





1
6
11
10


## Libraries

In [ ]:
import math
print(math.sqrt(16))  # => 4.0

In [36]:
# You can get specific functions from a module
from math import ceil, floor
print(ceil(3.7))   # => 4
print(floor(3.7))  # => 3

4.0
4
3


In [37]:
# You can import all functions from a module.
# Warning: this is not recommended
from math import *
print(sqrt(8))

2.8284271247461903


In [38]:
# You can shorten module names
import math as m
print(m.sqrt(16))

4.0


# Numpy

Numpy is a python library for doing scientific computing. It provides simplistic syntax and high performance array objects. If you're familiar with MATLAB you will find the syntax familiar.

## Array Declaration

In [57]:
import numpy as np # Convention

a = np.array([1, 2, 3])   # Create a rank 1 array
print('a shape:', a.shape)            # Prints "(3,)"
print('a:', a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print('b shape:', b.shape)                     # Prints "(2, 3)"
print('b:', b)

a shape: (3,)
a: [1 2 3]
b shape: (2, 3)
b: [[1 2 3]
 [4 5 6]]


## Accessing Arrays

### Accesing Elements

In [60]:
a = np.array([1, 2, 3])
b = np.array([[1,2,3],[4,5,6]])

print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)

print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"
print(b[0][0], b[0][1], b[1][0])   # Prints "1 2 4", but slower as b[0,0] gets the element in one go, but b[0][0] works by returning b[0] then get [0] of b[0]

1 2 3
[5 2 3]
1 2 4
1 2 4


### Slicing

In [40]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]    # Rank 1 view of the second row of a
col_r2 = a[:, 1:3]
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2 3]
                             #          [ 6 7]
                             #          [10 11]] (3, 2)"

[5 6 7 8] (4,)
[[ 2  3]
 [ 6  7]
 [10 11]] (3, 2)


In [64]:
# Indexing methods that work for lists also work for numpy arrays.
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = np.array([1,2,3,4,5,6,7,8,9])
print(b[::-1])
#prints [9 8 7 6 5 4 3 2 1]

[9 8 7 6 5 4 3 2 1]


### Integer Array Indexing

In [42]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a[[0, 2], [1, 0]])  # Gives [a[0,1],a[2,0]] which is [2 5]
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

[2 5]
[1 4 5]
[[11  2]
 [ 3 14]
 [15  6]]


## Array Maths

### Elementwise operations

In [65]:
x = np.array([[1.,2.],[3.,4.]])
y = np.array([[5.,6.],[7.,8.]])

# Elementwise sum;# [[ 6.0  8.0]
#                    [10.0 12.0]]
print(x + y)
# Elementwise difference;
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
# Elementwise product;
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
# Elementwise square root;
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


### Array Maths with Integer Array Indexing

In [68]:
a = np.array([[1,2], [3, 4], [5, 6]])
# Create an array of indices
b = np.array([0, 1, 0])
# Mutate one element from each row of a using the indices in b
print(a)
print(a[np.arange(3), b])
a[np.arange(3), b] += 10
print(a)  # prints "array([[11,  2],
          #                [ 3, 14],
          #                [15, 6]])

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[[11  2]
 [ 3 14]
 [15  6]]


### Boolean Array and Indexing

In [70]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.
print(a)
print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


### Matrix Products

In [74]:
x = np.array([[1.,2.],[3.,4.]])
v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; These 3 are equivalent
print(v.dot(w))
print(np.dot(v, w))
print(v @ w) # @ indicates a matrix multiplication operator

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

219
219
219
[29. 67.]
[29. 67.]
[29. 67.]
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


### sum

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(x.sum(axis=0))  # Equivalent to np.sum(x, axis=0)

print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

### arange

Works like range, but returns a numpy array

In [76]:
print(np.arange(1,10,2)) # Prints [1 3 5 7 9]

[1 3 5 7 9]


### flatten

Flattens high dimensional array in C order

In [99]:
x = np.array([[1,2],[3,4]])
print(x)
print(x.flatten())

[[1 2]
 [3 4]]
[1 2 3 4]


### einsum

Useful for physics students in manipulating tensors.

In [47]:
a = np.arange(25).reshape(5,5)
b = np.arange(5)
np.einsum('ii', a) #60 #Add all diagonal entries, a_ii
np.einsum('ii->i', a) #array([ 0,  6, 12, 18, 24]) #Get all diagonal entries, a_ii without summing
np.einsum('ij,j', a, b) #array([ 30,  80, 130, 180, 230]) #a_ij b_j, Matrix vector multiplication
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)
np.einsum('ijk,jil->kl', a, b) #a_ijk b_jil -> c_kl, rank 3 tensor contraction
#array([[ 4400.,  4730.],
#       [ 4532.,  4874.],
#       [ 4664.,  5018.],
#       [ 4796.,  5162.],
#       [ 4928.,  5306.]])

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])

## Array Broadcasting

![Broadcasting](img/broadcasting.png)

In [89]:
a = np.array([[0], [10], [20], [30]])
b = np.array([[0, 1, 2]])
print(a)
print(b)
print(a+b)
print(a*b)


[[ 0]
 [10]
 [20]
 [30]]
[[0 1 2]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  0  0]
 [ 0 10 20]
 [ 0 20 40]
 [ 0 30 60]]


In [82]:
a = np.ones((4, 5))
a[0] = 2  # we assign an array of dimension 0 to an array of dimension 
print(a) #array([[ 2.,  2.,  2.,  2.,  2.], 
         #       [ 1.,  1.,  1.,  1.,  1.],
         #       [ 1.,  1.,  1.,  1.,  1.],
         #       [ 1.,  1.,  1.,  1.,  1.]])

[[2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Strides (Optional)

You properly wont be using strides in the future but knowing them helps writing optimized code.

In [90]:
import numpy as np

x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype=np.int8)

#At which byte starting from x[0,0] does x[1,2] begins?

#Strides! Number of bytes to jump to reach the next element
print(x.strides) #=> (3,1)
#Jump 3 bytes to go to next column
#Jump 1 byte to go to next row

#Read x in C pointer style
byte_offset = 3*1 + 1*2 #Jump 1st column and 2nd row
print(x.flat[byte_offset]) #=> 6 #No out of bound checking

(3, 1)
6


### Array Shape Transformations with Strides

In [51]:
#A lot of transformation can be done by changing strides
#That means the transformed array is actually
#pointing to the same memory but reading in a different way.
#No copies made.
x = np.array([0, 1, 2, 3, 4, 5], dtype=np.int8)
y = x[::-1] #Read x in reverse
print(y) #=>[5 4 3 2 1 0]
print(y.strides) #=>(-1,)

#x and y are pointing to the same block of memory
#with different method to read and different first memory location
print(x.__array_interface__) #Gives a lot of metadata about x
print(y.__array_interface__)

#So changing y changes x as well
y[2] = 100
print(y) #[5 4 100 2 1 0]
print(x) #[0 1 2 100 4 5]

[5 4 3 2 1 0]
(-1,)
{'data': (94583837965616, False), 'strides': None, 'descr': [('', '|i1')], 'typestr': '|i1', 'shape': (6,), 'version': 3}
{'data': (94583837965621, False), 'strides': (-1,), 'descr': [('', '|i1')], 'typestr': '|i1', 'shape': (6,), 'version': 3}
[  5   4 100   2   1   0]
[  0   1   2 100   4   5]


In [100]:
#Sometimes a copy must be made

x = np.array([0, 1, 2, 3, 4, 5], dtype=np.int8)
z = x.reshape(3, 2)
print(z) #=> [[0 1]
         #    [2 3]
         #    [4 5]]
z = z.T
print(z) #=> [[0 2 4] 
         #    [1 3 5]]

a = z.reshape(3*2)
#There is no way to represent a with x by
#a one dimensional stride. So a copy is made.
#This takes O(n) time, while modifying strides is O(1)
print(a) # [0 2 4 1 3 5]

[[0 1]
 [2 3]
 [4 5]]
[[0 2 4]
 [1 3 5]]
[0 2 4 1 3 5]


### Manually Declaring Strides and Shape

In [92]:
from numpy.lib.stride_tricks import as_strided

#The same location of memory can appear several times in another array
x = np.array([1, 2, 3, 4], dtype=np.int8)
#Changing strides and the shape explicitly
y = as_strided(x, strides=(0, 1), shape=(3, 4))
print(y) # [[1 2 3 4]
         #  [1 2 3 4]
         #  [1 2 3 4]]
y[0,1] = 10 
print(y) # [[1 10 3 4]
         #  [1 10 3 4]
         #  [1 10 3 4]]
#Because y[0,0], y[0,1], y[0,2] occupies the same memory.

[[0 1]
 [2 3]
 [4 5]]
[[0 2 4]
 [1 3 5]]
[0 2 4 1 3 5]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[ 1 10  3  4]
 [ 1 10  3  4]
 [ 1 10  3  4]]


### Broadcasting with Strides

In [107]:
x = np.array([1, 2, 3, 4], dtype=np.int16)
x2 = as_strided(x, strides=(0, 1*2), shape=(3, 4))
y = np.array([5, 6, 7], dtype=np.int16)
y2 = as_strided(y, strides=(1*2, 0), shape=(3, 4))

print('x:', x)
print('y:', y)
print('x2:\n', x2)
print('y2:\n', y2)
print('manual broadcasting:\n', x2+y2) 
#[[5 10 15 20]
# [6 12 18 24]
# [7 14 21 28]]

#Which is actually equal to
print('numpy broadcasting\n', x[np.newaxis,:] + y[:,np.newaxis])
#array broadcasting is indeed implemented using 0-strides.

x: [1 2 3 4]
y: [5 6 7]
x2:
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
y2:
 [[5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]
manual broadcasting:
 [[ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]]
numpy broadcasting
 [[ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]]


In [108]:
#See the effect of cache locality here
x = np.zeros((20000,))
y = np.zeros((20000*67,))[::67]

#Run these 2 lines in ipython/jupyter, python doesn’t support these
%timeit x.sum() #100000 loops, best of 3: 0.180 ms per loop
%timeit y.sum() #100000 loops, best of 3: 2.34 ms per loop

print(x.strides, y.strides) #((8,), (536,))

7.54 µs ± 132 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
14.6 µs ± 27.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
(8,) (536,)
